openapi: 3.0.0
info:
  title: Swagger BookStore
  description: |
    Dentist Reservations  - Software Development - Mini project 2.
  contact:
    name: Developer - Fedor Vlasov
    email: AD9348@student.jamk.fi
  license:
    name: CoDeveloper - Khan Md Nayeem Hasan
    url: mailto:nayeembracu29@gmail.com
  version: 1.0.2
servers:
- url: https://dentist-reservations.swagger.io/v2
paths:
  /reservations:
    get:
      tags:
      - calendar
      summary: Get all reservations
      operationId: getAllReservations
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
                x-content-type: application/json
        "404":
          description: No reservations found
      x-swagger-router-controller: Calendar
    post:
      tags:
      - calendar
      summary: Add a new reservation
      operationId: addReservation
      responses:
        "201":
          description: Reservation added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
        "400":
          description: Invalid reservation data
      x-swagger-router-controller: Calendar
  /reservations/{reservationId}:
    put:
      tags:
      - calendar
      summary: Update an existing reservation
      operationId: updateReservation
      parameters:
      - name: reservationId
        in: path
        description: ID of the reservation to update
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Reservation updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
        "400":
          description: Invalid reservation data
        "404":
          description: Reservation not found
      x-swagger-router-controller: Calendar
    delete:
      tags:
      - calendar
      summary: Remove a reservation
      operationId: removeReservation
      parameters:
      - name: reservationId
        in: path
        description: ID of the reservation to remove
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "204":
          description: Reservation removed successfully
        "404":
          description: Reservation not found
      x-swagger-router-controller: Calendar
  /reservations/search:
    get:
      tags:
      - calendar
      summary: Search reservations
      operationId: searchReservations
      parameters:
      - name: service
        in: query
        description: Service provided by the customer
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: customerName
        in: query
        description: Customer name
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: timePeriod
        in: query
        description: Time period for the search
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date-time
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
                x-content-type: application/json
        "404":
          description: No reservations found for the specified criteria
      x-swagger-router-controller: Calendar
  /reservations/partialUpdate:
    patch:
      tags:
      - calendar
      summary: Partially update a reservation
      operationId: partialUpdateReservation
      responses:
        "200":
          description: Reservation partially updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
        "400":
          description: Invalid reservation data
        "404":
          description: Reservation not found
      x-swagger-router-controller: Calendar
components:
  schemas:
    Reservation:
      required:
      - customerId
      - endTime
      - service
      - startTime
      type: object
      properties:
        id:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        customerName:
          type: string
        service:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
      example:
        service: service
        customerId: 6
        startTime: 2000-01-23T04:56:07.000+00:00
        id: 0
        endTime: 2000-01-23T04:56:07.000+00:00
        customerName: customerName
      xml:
        name: Reservation
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
